name: Release and Deploy to Development

on:
  push:
    branches:
      - develop
    tags:
      - "**"

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTIONS_TOKEN }}

      - name: Build development and Push to ghcr
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.dev
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.tag }}
            ghcr.io/${{ github.repository }}:latest

      - name: Deploy to test server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker image prune -f
            docker pull ghcr.io/${{ github.repository }}:latest
            docker-compose -f docker-compose.dev.yml up -d
            docker ps
